#!/bin/bash

# Create home directories
mkdir -p ~/Pictures ~/Music ~/Downloads ~/Videos ~/Documents

# Install ZSH as the default shell
sudo chmod +x installScripts/installZsh && ./installScripts/installZsh

# Install st
sudo chmod +x installScripts/installSt && ./installScripts/installSt

# Install dmenu
sudo chmod +x installScripts/installDmenu && ./installScripts/installDmenu

# Copy config files for i3
cp -r ./config/i3 ~/.config
cp -r ./config/i3status ~/.config
cp -r ./config/dunst ~/.config
cp -r ./config/mpd ~/.config
cp -r ./config/ncmpcpp ~/.config
sudo cp config/i3exit /usr/bin

# Copy Ly config file
sudo cp ~/Debian-i3-Dotfiles/config/ly/config.ini /etc/ly/

# Copy custom scripts
mkdir -p ~/.local/ && cp -r bin ~/.local
chmod +x ~/.local/bin/*

# Copy .Xresources for color scheme
cp .Xresources ~/

# Copy wallpapers
cp -r ./wallpapers ~/Pictures

# Removes extra packages
cat ./packages/packages_remove.txt | xargs sudo apt remove -y
yes | rm -r ~/.mlterm

# Reduce grub timeout to 0
sudo sed -i "s/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g" /etc/default/grub

# Clean up system
./bin/aptm

# Reboot the system
sudo reboot
