#!/bin/bash

# Install packages
cat ./packages/packages_install.txt | xargs sudo apt install -y

# Install dependencies
cat ./packages/dependencies.txt | xargs sudo apt install -y

# Install Ly as the login manager
sudo chmod +x installScripts/installLy && ./installScripts/installLy

# Install Brave Browser
# sudo chmod +x installScripts/installBraveBrowser && ./installScripts/installBraveBrowser

# Install etcher
# sudo chmod +x installScripts/installEtcher && ./installScripts/installEtcher

# Reboot the system
sudo reboot
