#!/bin/bash

# Installs all the packages
cat ./packages/packages_install.txt | xargs sudo apt install

# Creates home directories
mkdir -p Pictures Music Downloads Videos Documents

# Installs Ly as the login manager
sudo chmod +x installScripts/installLy && ./installScripts/installLy

# Installs ZSH as the default shell
sudo chmod +x installScripts/installZsh && ./installScritps/installZsh
cp .zshrc ~/

# Copies the config files for i3
cp -r ./config/i3 ~/.config
cp -r ./config/i3status ~/.config
sudo cp config/i3exit /usr/bin/
sudo cp config/i3-dmenu-desktop /usr/bin

# Copies wallpapers
cp -r ./wallpapers/ ~/Pictures

# Copies custom scripts
mkdir -p ~/.local/ && cp -r bin/
chmod +x ~/.local/bin/*

# Installs Brave Browser
sudo chmod +x installScripts/installBraveBrowser && ./installScripts/installBraveBrowser

# Installs etcher
sudo chmod +x installScripts/installEtcher && ./installScripts/installEtcher

# Install themes
mkdir -p ~/.themes && cp themes/* ~/.themes/
mkdir -p ~/.icons && cp icons/* ~/.icons/

# Removes extra packages
cat ./packages/packages_remove.txt | xargs sudo apt remove

# Clean up system
./bin/aptm

sudo reboot
