#!/bin/bash

git clone https://github.com/cylgom/ly.git
cd ly
make github
sudo make install
sudo systemctl enable ly.service
cd ..
sudo rm -R ly
sudo cp ~/Debian-i3-Dotfiles/config/ly/config.ini /etc/ly/
